version: '3.3'
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - env-pgadmin.env
  flower:
    image: totem/celery-flower-docker
    env_file:
      - env-flower.env
